spring:
  prfiles:
    active: -dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: serverUserClient
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouduser?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: serverCloudApi.entitys
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance:
    instance-id: server-provider-user
  instance:
    prefer-ip-address: true
info:
  app:
    name: atguigu-microservicecloud
  company:
    name: www.atguigu.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: serverUserClient
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouduser?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: serverCloudApi.entitys
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/
  instance:
    instance-id: server-provider-user
  instance:
    prefer-ip-address: true
info:
  app:
    name: atguigu-microservicecloud
  company:
    name: www.atguigu.com
  build:
    artifactId: $project.artifactId$
    version: $project.version$

